name: ğŸ—‘ï¸ Delete Docker Image

run-name: Delete Docker image with tag ${{ github.event.inputs.image_tag }}

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag of the image to delete (e.g., a Git SHA)'
        required: true
        type: string

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          # NOTE: at now only orgs is supported
          owner: LSDAF
          name: lsadf_api
          # NOTE: using Personal Access Token
          token: ${{ secrets.GHCR_PAT }}
          tag: ${{ github.event.inputs.image_tag }}